# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=chatApplication

# JWT configuration
security.jwt.expiration-date=21600000
security.jwt.security-key=${JWT_SECRET_KEY}

# Optional: Disable dev tools in production
spring.devtools.restart.enabled=false
spring.jpa.hibernate.ddl-auto=validate