spring.data.mongodb.database=chatApplication
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true

security.jwt.security-key=4bbf5ef641e95aa5474f6f9e000b80e83e7c2e441cff743658aafd16a08234c6
security.jwt.expiration-date=21600000