spring.application.name=ChatApplication


spring.profiles.active= ${ENV:dev}




spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.servlet.multipart.enabled=true

server.tomcat.max-http-form-post-size=25MB
server.tomcat.max-swallow-size=25MB
server.error.whitelabel.enabled=false
server.error.include-exception=true
server.error.include-stacktrace=NEVER
server.error.include-message=ALWAYS



logging.level.org.mongodb.driver=WARN



publicId.default.userImage = userImage/62fa43c1-c63a-4e5c-b34e-d2edded0a376_default

publicId.default.groupChat = groupChat/f08f056e-b51c-4692-a2f6-5d9c12aaf1cc_defaultGroupChat