server.port=${PORT:8080}
# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=
spring.data.mongodb.auto-index-creation=true

# JWT configuration
security.jwt.expiration-date=21600000
security.jwt.security-key=${JWT_SECRET_KEY}

# Optional: Disable dev tools in production
spring.jpa.hibernate.ddl-auto=validate

logging.level.com.ChatApplication = info



server.error.include-stacktrace=NEVER
server.error.include-message=NEVER